
name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.REGISTRY_URL }}/project:${{ github.sha }}

    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v0.5.7
      with:
        host: ${{ secrets.DO_HOST }}
        username: ${{ secrets.DO_USER }}
        key: ${{ secrets.DO_SSH_KEY }}
        script: |
          docker pull ${{ secrets.REGISTRY_URL }}/project:${{ github.sha }}
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 8000:8000 ${{ secrets.REGISTRY_URL }}/project:${{ github.sha }}
